config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted,
  # simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here,
  # as Solidus relies on it being the default of "spree"

  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    root 'home#index'
    resources :products, only: :show
    resources :categories, only: :show
    resources :orders, only: [:show, :create, :edit, :update]
    resources :line_items, only: [:destroy]
    get :search, to: 'search#show'
    get '/checkout/:state', to: 'checkout#edit', as: :checkout_state
    patch '/checkout/update/:state', to: 'checkout#update', as: :update_checkout
    get '/cart', to: 'orders#edit'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/potepan/variant_decorator.rb
module Potepan::VariantDecorator
  def selectable_quantity
    total = total_on_hand
    total > 10 ? [*1..10] : [*1..total]
  end

  Spree::Variant.prepend self
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @search_form = ProductSearchForm.new(taxon: @taxon, color: params[:color], size: params[:size])
    @products = @search_form.search
    @taxonomies = Spree::Taxonomy.includes(root: :children)
    @option_type = Spree::OptionType.all
  end
end

app/controllers/potepan/checkout_controller.rb
class Potepan::CheckoutController < ApplicationController
  before_action :load_order, only: [:edit, :update]
  around_action :lock_order, only: [:edit, :update]
  before_action :set_state_if_present, only: [:edit, :update]
  before_action :ensure_order_not_completed, only: [:edit, :update]
  before_action :ensure_checkout_allowed, only: [:edit, :update]
  before_action :ensure_sufficient_stock_lines, only: [:edit, :update]
  before_action :ensure_valid_state, only: [:edit, :update]
  before_action :associate_user, only: [:edit, :update]
  before_action :setup_for_current_state, only: [:edit, :update]

  rescue_from Spree::Core::GatewayError, with: :rescue_from_spree_gateway_error

  def update
    if update_order
      unless transition_forward
        redirect_on_failure
        return
      end
      if @order.completed?
        redirect_to potepan_order_path(@order)
      else
        send_to_next_state
      end
    else
      render :edit
    end
  end

  private

  def update_order
    Spree::OrderUpdateAttributes.new(@order, update_params, request_env: request.headers.env).apply
  end

  def update_params
    if update_params = massaged_params[:order] # rubocop: disable Lint/AssignmentInCondition
      update_params.permit(permitted_checkout_attributes)
    else
      # We currently allow update requests without any parameters in them.
      {}
    end
  end

  def massaged_params
    massaged_params = params.deep_dup
    move_and_modifay_payment_source_into_payments_attributes(massaged_params)
    set_payment_parameters_amount(massaged_params, @order)
    massaged_params
  end

  def move_and_modifay_payment_source_into_payments_attributes(params)
    return params if params[:payment_source].blank?
    payment_params = params[:order] &&
                     params[:order][:payments_attributes] &&
                     params[:order][:payments_attributes].first
    return params if payment_params.blank?
    payment_method_id = payment_params[:payment_method_id]
    return params if payment_method_id.blank?
    expiry_all = params[:payment_source][payment_method_id][:expiry]
    expiry_month = expiry_all["value(2i)"]
    expiry_year = expiry_all["value(1i)"]
    expiry_month = "0#{expiry_month}" if expiry_month.to_i < 10
    expiry = "#{expiry_month} / #{expiry_year}"
    params[:payment_source][payment_method_id][:expiry] = expiry
    source_params = params[:payment_source][payment_method_id]
    return params if source_params.blank?
    payment_params[:source_attributes] = source_params
    params.delete(:payment_source)
    params
  end

  def transition_forward
    if @order.can_complete?
      @order.complete
    else
      @order.next
      @order.next if @order.state == "delivery"
    end
  end

  def redirect_on_failure
    flash[:error] = @order.errors.full_messages.join("\n")
    redirect_to(potepan_checkout_state_path(@order.state))
  end

  def send_to_next_state
    redirect_to potepan_checkout_state_path(@order.state)
  end

  def load_order
    @order = current_order
    redirect_to(potepan_root_path) && return unless @order
  end

  def set_state_if_present
    if params[:state]
      redirect_to potepan_checkout_state_path(@order.state) if @order.can_go_to_state?(params[:state]) # rubocop: disable Metrics/LineLength
      @order.state = params[:state]
    end
  end

  def ensure_order_not_completed
    redirect_to potepan_cart_path if @order.completed?
  end

  def ensure_checkout_allowed
    unless @order.checkout_allowed?
      redirect_to potepan_cart_path
    end
  end

  def ensure_sufficient_stock_lines
    if @order.insufficient_stock_lines.present?
      out_of_stock_items = @order.insufficient_stock_lines.collect(&:name).to_sentence
      flash[:error] = t(
        'spree.inventory_error_flash_for_insufficient_quantity', names: out_of_stock_items
      )
      redirect_to potepan_cart_path
    end
  end

  def ensure_valid_state
    if (params[:state] && !@order.has_checkout_step?(params[:state])) ||
       (!params[:state] && !@order.has_checkout_step?(@order.state))
      @order.state = 'cart'
      redirect_to potepan_checkout_state_path(@order.checkout_steps.first)
    end
  end

  def setup_for_current_state
    method_name = :"before_#{@order.state}"
    send(method_name) if respond_to?(method_name, true)
  end

  def before_address
    @order.assign_default_user_addresses
    # If the user has a default address, the previous method call takes care
    # of setting that; but if he doesn't, we need to build an empty one here
    default = { country_id: Spree::Country.find_by(name: "Japan").id }
    @order.build_bill_address(default) unless @order.bill_address
    @order.build_ship_address(default) if @order.checkout_steps.include?('delivery') && !@order.ship_address # rubocop: disable Metrics/LineLength, Airbnb/SimpleModifierConditional
  end

  def before_payment
    if @order.checkout_steps.include? "delivery"
      packages = @order.shipments.map(&:to_package)
      differentiator = Spree::Stock::Differentiator.new(@order, packages)
      differentiator.missing.each do |variant, quantity|
        @order.contents.remove(variant, quantity)
      end
    end
    @payment_method_id = @order.available_payment_methods.first.id
  end

  def rescue_from_spree_gateway_error(exception)
    flash.now[:error] = t('spree.spree_gateway_error_flash_for_checkout')
    @order.errors.add(:base, exception.message)
    redirect_to potepan_checkout_state_path("payment")
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAXIMUM_NUMBER_OF_NEW_PRODUCTS = 8
  MAXIMUM_NUMBER_OF_HOT_TAXONS = 3

  def index
    @new_products = Spree::Product.
      includes(master: [:images, :currently_valid_prices]).
      where("available_on > ?", 1.month.ago).
      order(available_on: :desc).
      limit(MAXIMUM_NUMBER_OF_NEW_PRODUCTS)
    @hot_taxons = Spree::Taxon.
      where("meta_keywords=?", "popularity").
      limit(MAXIMUM_NUMBER_OF_HOT_TAXONS)
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  before_action :assign_order

  def destroy
    @line_item = Spree::LineItem.find params[:id]
    @order.contents.remove_line_item(@line_item)
    @order.reload.line_items.present?
  end

  private

  def assign_order
    @order = current_order
    redirect_to(potepan_root_path) and return unless @order # rubocop: disable Style/AndOr
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  before_action :store_guest_token
  before_action :assign_order, only: :update
  before_action :ensure_completed_order, only: :show
  around_action :lock_order, only: :update

  def create
    @order = current_order(create_order_if_necessary: true)
    variant  = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].present? ? params[:quantity].to_i : 1
    # 2,147,483,647 is crazy. See issue https://github.com/spree/spree/issues/2695.
    if !quantity.between?(1, 2_147_483_647)
      @order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end
    begin
      @line_item = @order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => e
      @order.errors.add(:base, e.record.errors.full_messages.join(", "))
    end
    if @order.errors.any?
      flash[:error] = @order.errors.full_messages.join(", ")
      redirect_back(fallback_location: potepan_root_path) and return # rubocop: disable Style/AndOr
    else
      redirect_to potepan_cart_path
    end
  end

  def edit
    @order = current_order || Spree::Order.incomplete.find_or_initialize_by(
      guest_token: cookies.signed[:guest_token]
    )
    associate_user
  end

  def update
    if @order.contents.update_cart(order_params)
      @order.next if params.key?(:checkout) && @order.cart? # rubocop: disable Airbnb/SimpleModifierConditional, Metrics/LineLength
      if params.key?(:checkout)
        redirect_to potepan_checkout_state_path(@order.checkout_steps.first) and return # rubocop: disable Style/AndOr, Metrics/LineLength
      end
    end
    redirect_to potepan_cart_path
  end

  private

  def ensure_completed_order
    @order = Spree::Order.find_by(number: params[:id])
    redirect_back(fallback_location: potepan_cart_path) if @order.state != "complete"
  end

  def store_guest_token
    cookies.permanent.signed[:guest_token] = params[:token] if params[:token]
  end

  def order_params
    if params[:order]
      params[:order].permit(*permitted_order_attributes)
    else
      {}
    end
  end

  def assign_order
    @order = current_order
    redirect_to(potepan_root_path) and return unless @order # rubocop: disable Style/AndOr
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.available.friendly.find(params[:id])
    @product_images = (@product.images + @product.variant_images).uniq || []
    @taxons = @product.taxons
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/search_controller.rb
class Potepan::SearchController < ApplicationController
  def show
    @word = params[:search_word]
    @products = Spree::Product.words_search(params[:search_word])
    @taxonomies = Spree::Taxonomy.includes(root: :children)
  end
end

app/helpers/potepan/categories_helper.rb
module Potepan
  module CategoriesHelper
    def taxons_list(taxonomies)
      tag.ul id: "categories", class: "nav navbar-nav side-nav" do
        taxonomies.each do |taxonomy|
          taxon_root =  taxonomy.root
          list_connection(taxon_root, a_id: "category-parent") do
            tag.ul id: taxon_root.name, class: "collapse collapseItem" do
              taxon_root.children.each do |child|
                if child.children.empty?
                  concat lowest_list(child)
                else
                  list_connection(child, a_id: "category-child") do
                    tag.ul(id: child.name, class: "collapse collapseItem") do
                      child.children.each do |grandchild|
                        concat lowest_list(grandchild, li_class: "grandchild")
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end

    def lowest_list(taxon, li_class: nil)
      tag.li(class: "#{li_class}") do
        link_to potepan_category_path(taxon.id) do
          concat tag.i(class: "fa fa-angle-right", aria: { hidden: true })
          concat taxon.name
          concat tag.span "  (#{taxon.active_products.count})"
        end
      end
    end

    def list_connection(taxon, a_id: nil)
      icon_class = (a_id == "category-parent") ? "fa fa-plus" : "fa fa-caret-right"
      concat(
        tag.li do
          concat(
            link_to("javascript:;", class: a_id, data: {
              toggle: "collapse",
              target: "\##{taxon.name}",
            }) do
              concat taxon.name
              concat tag.i class: icon_class
            end
          )
          concat(
            yield
          )
        end
      )
    end

    def categories_title(search_form)
      title = search_form.taxon.name
      if search_form.color
        title += " / #{search_form.color}"
      end
      title
    end
  end
end

app/helpers/potepan/checkout_helper.rb
module Potepan
  module CheckoutHelper
    def select_render(state)
      if state == "address"
        return render('potepan/checkout/address') # rubocop: disable Style/RedundantReturn
      elsif state == "payment"
        return render('potepan/checkout/payment') # rubocop: disable Style/RedundantReturn
      elsif state == "confirm"
        return render('potepan/checkout/confirm') # rubocop: disable Style/RedundantReturn
      end
    end
  end
end

app/helpers/potepan/orders_helper.rb
module Potepan
  module OrdersHelper
    def line_item_name(line_item)
      option_value = line_item.variant.options_text
      if line_item.variant.is_master?
        line_item.name
      else
        "#{line_item.name} (#{option_value})"
      end
    end
  end
end

app/helpers/potepan/products_helper.rb
require 'carmen'

module Potepan
  module ProductsHelper
    include Spree::ProductsHelper

    def taxon_or_home_link(product_taxons)
      if product_taxons.empty?
        potepan_root_path
      else
        potepan_category_path(product_taxons.ids[0])
      end
    end

    MAXIMUM_NUMBER_OF_DISPLAYS = 4

    def taxon_products(product_taxons, exclude_product_id)
      if product_taxons.empty?
        []
      else
        Spree::Product.in_taxons(product_taxons).distinct.
          with_images_and_prices.
          where.not(id: exclude_product_id).
          limit(MAXIMUM_NUMBER_OF_DISPLAYS)
      end
    end

    def select_box_of_variant(product)
      if product.has_variants?
        select_tag(:variant_id,
                   options_from_collection_for_select(product.variants_and_option_values_for,
                                                      :id,
                                                      :options_text))
      else
        hidden_field_tag(:variant_id, product.master.id)
      end
    end

    def variants_assign(product)
      backorderable_no_stock = []
      no_backorderable_stock = []
      no_backorderable_no_stock = []
      variant_array = product.has_variants? ? product.variants : [product.master]
      variant_array.each do |variant|
        if variant.is_backorderable? && !variant.in_stock?
          backorderable_no_stock << variant.id
        elsif !variant.is_backorderable? && variant.in_stock?
          no_backorderable_stock << variant.id
          concat select_tag :quantity,
                            options_for_select(variant.selectable_quantity, 1),
                            id: "quantity-items#{variant.id}",
                            hidden: true
        elsif !variant.is_backorderable? && !variant.in_stock?
          no_backorderable_no_stock << variant.id
        end
      end
      tag.div(hidden: true) do
        concat tag.div backorderable_no_stock.join(","), id: "backorderable_no_stock"
        concat tag.div no_backorderable_stock.join(","), id: "no_backorderable_stock"
        concat tag.div no_backorderable_no_stock.join(","), id: "no_backorderable_no_stock"
      end
    end
  end
end

app/views/potepan/checkout/_address.html.erb
<%= provide(:header_title, "お届け先情報") %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix stepsWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="innerWrapper clearfix stepsPage">
          <div class="row progress-wizard" style="border-bottom:0;">
            <div class="col-xs-4 progress-wizard-step complete">
              <div class="text-center progress-wizard-stepnum">お届け先情報</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>
            <div class="col-xs-4 progress-wizard-step disabled">
              <div class="text-center progress-wizard-stepnum">お支払い方法</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>
            <div class="col-xs-4 progress-wizard-step disabled">
              <div class="text-center progress-wizard-stepnum">入力内容確認</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>
          </div>
          <%= form_for @order, url: potepan_update_checkout_path(@order.state), html: { class: "row", role: "form", id: "checkout_form_address" } do |order_form| %>

            <div class="col-xs-12">
              <%= render 'shared/error_messages', object: order_form.object %>
              <div class="page-header">
                <h4>請求先</h4>
              </div>
            </div>
            <div class="billing_info_form">
              <%= order_form.fields_for :bill_address do |bill_form| %>
                <div class="form-group col-sm-6 col-xs-12">
                  <%= bill_form.label :lastname, '姓' %>
                  <%= bill_form.text_field :lastname, class: "form-control" %>
                </div>
                <div class="form-group col-sm-6 col-xs-12">
                  <%= bill_form.label :firstname, '名' %>
                  <%= bill_form.text_field :firstname, class: "form-control" %>
                </div>

                <div class="form-group col-sm-6 col-xs-12">
                  <%= order_form.label :email, 'メールアドレス' %>
                  <%= order_form.email_field :email, class: "form-control" %>
                </div>
                <div class="form-group col-sm-6 col-xs-12">
                  <%= bill_form.label :phone, '電話番号' %>
                  <%= bill_form.telephone_field :phone, class: "form-control", pattern: "[0-9]{2,3}-[0-9]{3,4}-[0-9]{4,5}", title: "電話番号は、ハイフン（-）を入れて記入してください。"%>
                </div>

                <div class="form-group col-sm-6 col-xs-12">
                  <%= bill_form.label :zipcode, '郵便番号' %>
                  <%= bill_form.telephone_field :zipcode, class: "form-control", pattern: "[0-9]{3}-[0-9]{4}", title: "郵便番号は、ハイフン（-）を入れて記入してください。", maxlength: 8 %>
                </div>
                <div class="form-group col-sm-6 col-xs-12">
                  <%= bill_form.label :country_id, '国' %>
                  <%= bill_form.collection_select :country_id, [Spree::Country.find_by(name: "Japan")], :id, :name %>
                </div>

                <div class="form-group col-sm-6 col-xs-12">
                  <%= bill_form.label :state_id, '都道府県' %>
                  <%= bill_form.collection_select :state_id, Spree::State.where(country_id: Spree::Country.find_by(name: "Japan").id), :id, :name %>
                </div>
                <div class="form-group col-sm-6 col-xs-12">
                  <%= bill_form.label :city, '市' %>
                  <%= bill_form.text_field :city, class: "form-control" %>
                </div>

                <div class="form-group col-sm-6 col-xs-12">
                  <%= bill_form.label :address1, '住所' %>
                  <%= bill_form.text_field :address1, class: "form-control" %>
                </div>
              <% end %>
            </div>
            <div class="col-xs-12">
              <div class="page-header"  id="bill-form-header">
                <h4>配送先</h4>
                <%= order_form.check_box :use_billing, checked: true %>
                <%= order_form.label :use_billing, "請求先の情報を使う" %>
              </div>
            </div>
            <div class="shipping_info_form">
              <%= order_form.fields_for :ship_address do |ship_form| %>
                <div class="form-group col-sm-6 col-xs-12">
                  <%= ship_form.label :lastname, '姓' %>
                  <%= ship_form.text_field :lastname, class: "form-control" %>
                </div>
                <div class="form-group col-sm-6 col-xs-12">
                  <%= ship_form.label :firstname, '名' %>
                  <%= ship_form.text_field :firstname, class: "form-control" %>
                </div>


                <div class="form-group col-sm-6 col-xs-12">
                  <%= ship_form.label :phone, '電話番号' %>
                  <%= ship_form.telephone_field :phone, class: "form-control", pattern: "[0-9]{2,3}-[0-9]{3,4}-[0-9]{4,5}", title: "電話番号は、ハイフン（-）を入れて記入してください。"%>
                </div>
                <div class="form-group col-sm-6 col-xs-12">
                  <%= ship_form.label :zipcode, '郵便番号' %>
                  <%= ship_form.telephone_field :zipcode, class: "form-control", pattern: "[0-9]{3}-[0-9]{4}", title: "郵便番号は、ハイフン（-）を入れて記入してください。", maxlength: 8 %>
                </div>

                <div class="form-group col-sm-6 col-xs-12">
                  <%= ship_form.label :country_id, '国' %>
                  <%= ship_form.collection_select :country_id, [Spree::Country.find_by(name: "Japan")], :id, :name %>
                </div>
                <div class="form-group col-sm-6 col-xs-12">
                  <%= ship_form.label :state_id, '都道府県' %>
                  <%= ship_form.collection_select :state_id, Spree::State.where(country_id: Spree::Country.find_by(name: "Japan").id), :id, :name %>
                </div>

                <div class="form-group col-sm-6 col-xs-12">
                  <%= ship_form.label :city, '市' %>
                  <%= ship_form.text_field :city, class: "form-control" %>
                </div>
                <div class="form-group col-sm-6 col-xs-12">
                  <%= ship_form.label :address1, '住所' %>
                  <%= ship_form.text_field :address1, class: "form-control" %>
                </div>
              <% end %>
            </div>
            <div class="col-xs-12">
              <div class="well well-lg clearfix cartListInner">
                <ul class="pager checkBtnArea" id="address-button">
                  <li class="previous"><%= link_to "back", potepan_cart_path %></li>
                  <li class="next"><%= button_tag "次へ", class: "btn btn-primary btn-block", aria: { hidden: true } %></li>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/checkout/_confirm.html.erb
<%= provide(:header_title, "お支払い方法") %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix stepsWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="innerWrapper clearfix stepsPage">
          <div class="row progress-wizard" style="border-bottom:0;">
            <div class="col-xs-4 progress-wizard-step complete fullBar">
              <div class="text-center progress-wizard-stepnum">お届け先情報</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>
            <div class="col-xs-4 progress-wizard-step complete fullBar">
              <div class="text-center progress-wizard-stepnum">お支払い方法</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>
            <div class="col-xs-4 progress-wizard-step complete">
              <div class="text-center progress-wizard-stepnum">入力内容確認</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>
          </div>
          <form action="" class="row" method="POST" role="form">
            <div class="col-xs-12">
              <div class="page-header">
                <h4>入力内容確認</h4>
              </div>
            </div>
            <div class="col-sm-12 col-xs-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">お届け先情報</h4>
                </div>
                <div class="panel-body">
                  <address>
                    <strong><%= @order.name %></strong><br>
                    <%= @order.ship_address.zipcode %><br>
                    <%= "#{@order.ship_address.country.try(:name)}  #{@order.ship_address.state.name}" %><br>
                    <%= "#{@order.ship_address.city}  #{@order.ship_address.address1}" %>
                  </address>
                </div>
              </div>
            </div>
            <div class="col-xs-12">
              <div class="cartListInner">
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th></th>
                        <th>商品名</th>
                        <th>価格（税抜）</th>
                        <th>数</th>
                        <th>小計（税抜）</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @order.line_items.each do |item| %>
                        <tr class="lineitem">
                          <td class="col-xs-2">
                            <span class="cartImage"><%= image_tag(item.variant.gallery.images.first.url(:mini), alt: 'image') if item.variant.gallery.images.first.try(:url, :mini) %></span>
                          </td>
                          <td class="col-xs-4"><%= link_to line_item_name(item), potepan_product_path(item.product), class: "cart-product-name" %></td>
                          <td class="col-xs-2"><%= Spree::Money.parse((item.total_excluding_vat / item.quantity)) %></td>
                          <td class="col-xs-2"><%= item.quantity %></td>
                          <td class="col-xs-2"><%= item.display_total_excluding_vat %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <div class="row totalAmountArea">
                  <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                    <ul class="list-unstyled">
                      <li>小計 <span id="subtotal-cart"><%= Spree::Money.parse(@order.item_total_excluding_vat) %></span></li>
                      <li>消費税 <span id="tax-amount"><%= @order.display_included_tax_total %></span></li>
                      <li>配送料 <span id="tax-amount"><%= @order.display_ship_total %></span></li>
                      <li>総計 <span class="grandTotal"><%= @order.display_total %></span></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xs-12">
              <div class="well well-lg clearfix cartListInner">
                <ul class="pager checkBtnArea" id="address-button">
                  <li class="previous"><%= link_to "back", potepan_checkout_state_path("payment") %></li>
                  <li class="next"><%= link_to "購入確定", potepan_update_checkout_path(@order.state), method: :patch %></li>
                </ul>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/checkout/edit.html.erb
<%= render "shared/error_checkout_messages" if flash[:error].present? %>
<%= select_render(@order.state) %>