config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted,
  # simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here,
  # as Solidus relies on it being the default of "spree"

  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'

    root 'home#index'
    resources :products, only: :show
    resources :categories, only: :show
    resources :orders, only: [:show, :create, :edit, :update]
    resources :line_items, only: [:destroy]
    get :search, to: 'search#show'
    get '/checkout/:state', to: 'checkout#edit', as: :checkout_state
    patch '/checkout/update/:state', to: 'checkout#update', as: :update_checkout
    get '/cart', to: 'orders#edit'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.zone.now.year %> Copyright Potepan Store .</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <%= render 'layouts/topbar' %>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to(image_tag("img/logo.png", alt: ""), potepan_root_path, class: "navbar-brand") %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Home", potepan_root_path %>
          </li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
</div>
<%= select_light_section(header_title) %>

app/views/layouts/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <%= tag.h2 header_title %>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right header-title">
          <li>
            <%= link_to "Home", potepan_root_path %>
          </li>
          <%= tag.li(header_title, class: "active") unless header_title == "Home" %>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_topbar.html.erb
<!-- TOPBAR -->
<div class="topBar">
  <div class="container">
    <div class="row">
      <div>
        <ul class="list-inline pull-right">
          <li class="dropdown searchBox">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <%= form_tag('/potepan/search', method: "get", id: "form01") do %>
                <li>
                  <span class="input-group topbar-search">
                    <%= text_field_tag(:search_word, '', { class: "form-control", placeholder: "Search…", aria: { describedby: "basic-addon2" } })%>
                    <%= submit_tag "検索", class: "input-group-addon addPointer", id: "basic-addon2" %>
                  </span>
                </li>
              <% end %>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="topbar-shoppting-cart"><i class="fa fa-shopping-cart"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li>Item(s) in your cart</li>
              <% if current_order %>
                <% current_order.line_items.each do |item| %>
                  <li class="<%= "lineitem-#{item.id}" %>">
                    <%= link_to potepan_product_path(item.product) do %>
                      <div class="media">
                        <%= image_tag(item.variant.gallery.images.first.url(:mini), class: "media-left media-object", alt: 'cart-Image') if item.variant.gallery.images.first.try(:url, :mini) %>
                        <div class="media-body">
                          <h5 class="media-heading"><%= item.name %><br><span><%= item.quantity %> X <%= item.display_price %></span></h5>
                        </div>
                      </div>
                    <% end %>
                  </li>
                <% end %>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <%= button_tag "Shopping Cart", type: 'button', onclick: "link_to('#{potepan_cart_path}')", class: "btn btn-default" %>
                    <%= button_tag "Checkout", type: 'button', onclick: "link_to('#{potepan_checkout_state_path(current_order.state)}')", class: "btn btn-default" %>
                  </div>
                </li>
              <% else %>
                <li>カートに追加された商品はありません。</li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(page_title: yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

    <!-- CUSTOM CSS -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header', header_title: yield(:header_title) %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>